version: '2.1'
services:
  vault:
    image: hashicorp/vault
    ports:
      - "8200:8200"
    container_name: "vault"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: secret_bro
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
      VAULT_ADDR: "http://vault:8200"
      VAULT_TOKEN: secret_bro
    healthcheck:
      test: [ "CMD", "vault", "status" ]
      interval: 3s
      retries: 3
      timeout: 3s
  vault-init:
    image: hashicorp/vault
    depends_on:
      vault:
        condition: service_healthy
    environment:
      VAULT_ADDR: "http://vault:8200"
      VAULT_TOKEN: secret_bro
    volumes:
      - ./vault-init.sh:/app/vault-init.sh
    command: [ "/bin/sh", "-c", "/app/vault-init.sh" ]
