spring.application.name=ExamensSubjectsInformerMicro

server.port=8086

# Will search for a Consumer bean with name subjectsProcessor, will add -in-0 in the end and will use it...
spring.cloud.stream.bindings.subjectsProcessor-in-0.destination=subjects-topic
spring.cloud.stream.bindings.subjectsProcessor-in-0.content-type=application/json
spring.cloud.stream.bindings.subjectsProcessor-in-0.group=subjects-group

spring.cloud.stream.kafka.binder.brokers=localhost:9092
spring.cloud.stream.kafka.binder.auto-offset-reset=earliest


# Notes:
#spring:
#  cloud:
#    stream:
#      default-binder: kafka
#      kafka:
#        binder:
#          brokers: ${KAFKA_URL:${KAFKA_HOST:localhost}}:${KAFKA_PORT:9092}
#          auto-create-topics: true
#      bindings:
#        accountRegistrations-in-0:
#          destination: account.registrations
#          content-type: application/json
#         group: group-name
#    function:
#      definition: accountRegistrations 
    # When there's only one function, you can omit the name of the function here, but if you have multiple functions, you must specify the name here.
    
    # In the code consumer can be represented with Consumer or Function. Consumer only reads from the queue, Function reads from the queue and writes to the output queue. For this you must have <binding-name>-in-0 and <binding-name>-out-0. This is perfect for enriching.
    # If you need to publish messages conditionally, then you should use StreamBridge and in this case you can pick any binding name.

    # These -in and -out postfixes are required by Spring Cloud Stream auto binding. When request came to -in binding, it's processed by the Function consumer, then Spring can automatically find the outgoing binding and publish the response.
